# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

pusher_facebook_key: "1436948926602803"
pusher_facebook_secret: "0da6a31f873ff08a923e2e3880c47a08"

pusher_email_user_name: 'team.goaly@gmail.com'
pusher_email_password: 'flatIronGoalies123'

pusher_twilio_account_sid: "AC5fe0b95954eb6fdd314b6cb0cb1297f6"
pusher_twilio_auth_token: "b024aabb1c2eeaa0327cc77d27b96deb"